language: node_js

node_js:

  - "7"

script:

 - echo "Deploy!!"

install:

  - npm install -g firebase-tools

after_success:

  - firebase deploy --project lastreclacia --token 1//03UG6oOEwnS3rCgYIARAAGAMSNwF-L9IrEpRfw1i1U4Qzgisuu8DBQSI-18nnMLf1yNolGtgUmgj6Pp0ygYdeOMXXE-LvhQxJW58
